import Head from "next/head";

export function Home() {
   return (
      <div>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main>hello</main>
      </div>
   );
}

//create the html container with custom container size in tailwind
//custom colors in tailwind
