import Head from "next/head";
import data from "data/data";

import Header from "./Header";
import CardContainer from "./CardContainer";

export function Home() {
   return (
      <div className="bg-grey min-h-screen">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className="container mx-auto p-5 ">
            <Header />
            <CardContainer data={data} />
         </main>
      </div>
   );
}

//create the html container with custom container size in tailwind
//custom colors in tailwind
